# Generated by Django 2.1.2 on 2018-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181113_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cursos',
            field=models.ManyToManyField(null=True, to='core.Curso'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projetodepesquisa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
