# Generated by Django 2.1.2 on 2018-11-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181113_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='nome_curso',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='cursos',
            field=models.ManyToManyField(to='core.Curso'),
        ),
    ]
