# Generated by Django 2.1 on 2018-12-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181126_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='descricao',
            field=models.CharField(default='Instruir os alunos do departamento', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='quantidadeAlunos',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='quantidadeProfessores',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='departamento',
            name='siglaDepartamento',
            field=models.CharField(max_length=3, null=True, verbose_name='sigla do departamento'),
        ),
    ]
