# Generated by Django 2.1.3 on 2018-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181203_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
