# Generated by Django 2.1.3 on 2018-12-03 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181203_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
